#!/bin/bash -el
git-update-server-info
gitosis-run-hook update-mirrors
app_dir=${PWD##*/}
app_name=${app_dir/.git/}
echo "Running push hook..."
url="${TSURU_HOST}/apps/${app_name}/repository/clone"
result=$(curl -s -N --max-time 1800 $url)
cat <<END
${result}
END
