#!/usr/bin/env python

import urllib2


# tsuru_host = os.environ.get("TSURU_HOST", "")
# app_name = os.getcwd().split("/")[-1].replace(".git", "")
tsuru_host = "http://ec2-23-22-70-116.compute-1.amazonaws.com:8080"
app_name = "bla4"
timeout = 1800

f = urllib2.urlopen("{0}/apps/{1}/avaliable".format(tsuru_host, app_name), timeout=timeout)
if f.getcode() != 200:
    print f.read()
    sys.exit(1)
